server.port=8082
services.account.base-url=http://account-service
services.managed-account.base-url=http://account-service
services.customer.base-url=http://customer-service
services.payment.base-url=http://payment-service
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_ISSUER:https://localhost:9000}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_JWK_SET_URI:http://auth-server:9000/oauth2/jwks}
spring.security.oauth2.resourceserver.jwt.audiences=bff-mobile
