server.port=${SERVER_PORT:8092}
spring.datasource.url=${PAYMENT_DB_URL:jdbc:mysql://localhost:3306/bancoxyz_payments}
spring.datasource.username=${PAYMENT_DB_USERNAME:bancoxyz_payment}
spring.datasource.password=${PAYMENT_DB_PASSWORD}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_ISSUER:https://localhost:9000}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_JWK_SET_URI:http://auth-server:9000/oauth2/jwks}
spring.security.oauth2.resourceserver.jwt.audiences=payment-service
spring.flyway.clean-disabled=true
